### ISSUE TITLE
[Feature Request]:

### ISSUE THREAD

**Issue by theolaa** [VueTorrent/VueTorrent#2178]
### Description

At the moment, incomplete torrents show their completion date as `1970-01-01 00:00:00`. I understand why it appears that way, but it's misleading to have that as the completion date, and hinders one's ability to parse that column.

### Describe the solution you'd like

It would be mildly easier to parse that column if instead it appeared as `N/A` or some other indicator that it is not completed.

### Complementary informations

- [ ] Is this feature already implemented in the default WebUI?

**Comment by cheneyni-451** [comment]
This issue seems to already be resolved in the latest release. Incomplete torrents show their "Completed On" value as "Never seen complete" on the dashboard and as "N/A" on the details view.

**Comment by theolaa** [comment]
I'm on 2.22.0, I'll check out 2.23.0 and see

**Comment by theolaa** [comment]
I upgraded to 2.23.0 and I still have the behaviour I described. The "Completed On" column displays the 1970 date, as does the info chip in the dashboard:
![Image](https://github.com/user-attachments/assets/4152a3f2-6fb5-4934-b849-150bdc3df24d)

![Image](https://github.com/user-attachments/assets/baf45883-f3cb-48ed-a60a-3c6c7ef8fd10)

![Image](https://github.com/user-attachments/assets/5b370e60-382a-47fa-b60d-4c50589a6312)

**Comment by cheneyni-451** [comment]
Oh, this might be a qBittorrent version issue then. I tested it on qBittorrent v5.0.4 and VueTorrent v2.23.0.

**Comment by Larsluph** [comment]
In that case, I'll need the value returned by qBittorrent to better understand the real issue here.

qBittorrent did change the way they handle this field in 5.0

https://github.com/qbittorrent/qBittorrent/commit/ad22237a2f50f9a636ed39bfc3f70e32c0e439ea#diff-74790edbe4766657bffad7700b1a73f606a7692cee56f1e093c7357ecdaea915R139

Here's the [wiki link](https://github.com/VueTorrent/VueTorrent/wiki/Support#how-to-view-network-requests) for checking network requests.
Fetching this field is a bit complicated but you need to open your DevTools **before** opening VueTorrent. Then the field will be in the `maindata` request, expand the torrent hash causing the bug and send the "completion_on" field

**Comment by cheneyni-451** [comment]
I just tested with qBittorrent v4.6.3. It seems like the `completion_on` field is returning the date-time `1970-01-01 00:00:00` of your system timezone as seconds since Unix epoch. So if your timezone is UTC-8, `completion_on` would be 28800, 0 for UTC+0, and -3600 for UTC+1.

**Comment by Larsluph** [comment]
But the UI should display the not complete message for all "invalid" dates, that is 0 or negative values. The issue shouldn't happen the way you describe it.

What do you receive exactly as the value when it displays the 1970 date?

**Comment by cheneyni-451** [comment]
I was testing different timezones by changing my system timezone using `timedatectl`. The UI displays `1970-01-01 00:00:00` for incomplete torrents when your timezone is west of UTC (e.g. UTC-8). I'm getting a `completed_on` value of 28800 for UTC-8. The UI correctly displays "Never seen complete" when the timezone is UTC+, for which `completed_on` has a 0 or negative value.

A possible hack is to change the condition for displaying the date-time from `val > 0` to `val > 43200` (`12 * 60 * 60`) to account for all timezones up to UTC-12

**Comment by theolaa** [comment]
Maybe I'm not looking in the right place, but this is a `/properties` request for an in-progress torrent:
The only seemingly relevant field is the `completion_date` (3rd from the top) which is set to `-1`.

![Image](https://github.com/user-attachments/assets/f842f0c9-3f31-412e-8d2b-90008e1982e4)

**Comment by Larsluph** [comment]
Depending on where you look, this is the same field but with different names.

---

qBit v5+:

In `serialize_torrent.cpp` (maindata):
```cpp
{KEY_TORRENT_COMPLETION_ON, Utils::DateTime::toSecsSinceEpoch(torrent.completedTime())},
```

In `torrentscontroller.cpp` (properties):
```cpp
{KEY_PROP_COMPLETION_DATE, Utils::DateTime::toSecsSinceEpoch(torrent->completedTime())},
```

Converter function:
```cpp
qint64 Utils::DateTime::toSecsSinceEpoch(const QDateTime &dateTime)
{
    return dateTime.isValid() ? dateTime.toSecsSinceEpoch() : -1;
}
```

---

qBit v4.6.7:

In `serialize_torrent.cpp` (maindata):
```cpp
{KEY_TORRENT_COMPLETION_ON, toTimeStamp(torrent.completedTime())},
```

In `torrentscontroller.cpp` (properties):
```cpp
{KEY_PROP_COMPLETION_DATE, toTimeStamp(torrent->completedTime())},
```

Converter function:
```cpp
const auto toTimeStamp = [](const QDateTime &dateTime) -> qint64
{
    return dateTime.isValid() ? dateTime.toSecsSinceEpoch() : -1;
};
```

---

Given that all of these leads to the same code, it shouldn't differ in behaviour. If we take a look at how torrents data is updated, we can see that the code is also identical.

For qBit 5+:
```cpp
if (m_nativeStatus.completed_time != oldStatus.completed_time)
  m_completedTime = (m_nativeStatus.completed_time > 0) ? QDateTime::fromSecsSinceEpoch(m_nativeStatus.completed_time) : QDateTime();
```

For qBit 4.6.7:
```cpp
QDateTime TorrentImpl::completedTime() const
{
  if (m_nativeStatus.completed_time > 0)
      return QDateTime::fromSecsSinceEpoch(m_nativeStatus.completed_time);
  else
      return {};
}
```

From [Qt docs](https://doc.qt.io/qt-6/qdatetime.html#fromSecsSinceEpoch-1:~:text=year%201970%2C%20described%20as%20specified%20by%20timeZone.-,The%20default%20time%20representation%20is%20local%20time.,-Note%20that%20there%20are%20possible%20values%20for%20secs), the default is to use the local timezone for the `fromSecsSinceEpoch` method, which confirms the bug.

I think in the end that the behaviour did not change.

@cheneyni-451 if you installed qBittorrent using docker or any other virtualization technology, changing your system timezone will not change anything. Each virtualization uses differnet method for this. The docker image may use a variable environment or a volume mount.
